spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
    password: 612853
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create